language: cpp
dist: bionic
sudo: require
compiler: gcc

before_install: 
 - sudo pip install codecov

script: 
 - qmake travis_qmake_gcc_cpp98_gcov.pro
 - make
 - ./travis_qmake_gcc_cpp98_gcov
 - ./get_code_cov
 - codecov

after_success:
 - bash <(curl -s https://codecov.io/bash)
